# Generated by Django 2.2.2 on 2020-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20200419_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message/images/', verbose_name='上传的文件'),
        ),
    ]
